version: '3.8'

services:
  bot:
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - bot-network

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=solanabot
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  postgres-data: